import {EmbeddingModel} from "./embedding.model";
import {MultiLanguageModel} from "./metadata.model";

type RefreshSchedule = "daily" | "hourly" | "weekly" | "monthly" | "yearly";

export class BusinessMetricModel {
    metric_id: string;
    type: "business_metric" | string;
    database_id: string;
    metric_name: BusinessMetricNameModel
    short_name: string;
    description: MultiLanguageModel
    business_domain: string;
    calculation_logic: string;
    sql_expression: string;
    relevant_table_ids: string[];
    relevant_column_ids: string[];
    unit_of_measure: string;
    aggregation_type: string;
    grain: "customer" | "order" | "program" | "product" | "channel" | "promotion" | "basket" | "item" | "transaction" | string;
    business_owner: string;
    refresh_schedule: RefreshSchedule
    refreshed_at: string;
    typical_range: TypicalRangeModel;
    related_metrics: string[];
    common_filters: string[];
    tags: string[];
    usage_frequency: number;
    last_queried: string;
    model?: string;
    structure?: string;
    brand_ref?: string;
    created_at?: string;
    updated_at?: string;

    [key: string]: any;
}

export class BusinessMetricWithVectorModel extends BusinessMetricModel {
    embedding: EmbeddingModel;

}

export class TypicalRangeModel {
    min: number;
    median: number;
    p95: number;
    max: number;
}



export class BusinessMetricNameModel {
    en: string;
    th: string;

    [key: string]: string;
}

const sampleMetric = [
    {
        metric_id: '7c5a3d91-4b2e-4f19-a8c7-9e2f1b8d6c4a',
        type: 'business_metric',
        database_id: '46cb1ce1-848b-4561-bed7-1f35c1a81a5c',
        metric_name: {
            en: 'Customer Lifetime Value',
            th: 'มูลค่าตลอดชีพของลูกค้า',
        },
        short_name: 'CLV',
        description: {
            en: 'Total revenue generated by a customer across all orders since enrollment. Used for customer segmentation and marketing budget allocation.',
            th: 'รายได้รวมที่ลูกค้าสร้างจากคำสั่งซื้อทั้งหมดนับตั้งแต่ลงทะเบียน ใช้สำหรับการแบ่งกลุ่มลูกค้าและจัดสรรงบการตลาด',
        },
        business_domain: 'customer-analytics',
        calculation_logic:
            'SUM(Order_Total) grouped by CustomerId for all completed orders',
        sql_expression:
            'SELECT CustomerId, SUM(Order_Total) AS CLV FROM dbo.CRM_Order GROUP BY CustomerId',
        relevant_table_ids: ['b1c181fd-3af6-4af9-9ce8-bb0fdd5ef884'],
        relevant_column_ids: [
            'b4f5ed31-2901-435d-95a7-4f87cb6805b6',
            '64eaa9b2-a63e-44c7-9f76-8738cd0d80a9',
        ],
        unit_of_measure: 'THB',
        aggregation_type: 'SUM',
        grain: 'customer',
        business_owner: 'crm-analytics',
        refresh_schedule: 'daily',
        typical_range: {
            min: 100,
            median: 2450,
            p95: 18500,
            max: 250000,
        },
        related_metrics: ['avg_order_value', 'order_frequency'],
        common_filters: ["registration_date >= '2024-01-01'", 'Point_Balance > 0'],
        tags: ['revenue', 'customer', 'kpi'],
        usage_frequency: 342,
        last_queried: '2025-09-28T14:32:00Z',
        embedding: {
            model: 'openai/text-embedding-3-small',
            dimension: 1536,
            vector: '[... 1536 dimensions ...]',
            generated_at: '2025-09-29T10:15:00Z',
            source:
                'metric_name + description + calculation_logic + common_business_questions',
        },
    },
    {
        metric_id: 'a3f7e9d2-8c1b-4a5e-9f3d-7b6c2e4a1d8f',
        type: 'business_metric',
        database_id: '46cb1ce1-848b-4561-bed7-1f35c1a81a5c',
        metric_name: {
            en: 'Average Order Value',
            th: 'มูลค่าเฉลี่ยต่อคำสั่งซื้อ',
        },
        short_name: 'AOV',
        description: {
            en: 'Mean transaction value per order. Key metric for promotional effectiveness and basket optimization.',
            th: 'มูลค่าธุรกรรมเฉลี่ยต่อคำสั่งซื้อ ตัวชี้วัดสำคัญสำหรับประสิทธิภาพโปรโมชั่นและการเพิ่มมูลค่าตะกร้า',
        },
        business_domain: 'sales-analytics',
        calculation_logic: 'Average of Order_Total across all orders',
        sql_expression: 'SELECT AVG(Order_Total) AS AOV FROM dbo.CRM_Order',
        relevant_table_ids: ['b1c181fd-3af6-4af9-9ce8-bb0fdd5ef884'],
        relevant_column_ids: ['64eaa9b2-a63e-44c7-9f76-8738cd0d80a9'],
        unit_of_measure: 'THB',
        aggregation_type: 'AVG',
        grain: 'order',
        business_owner: 'sales-ops',
        refresh_schedule: 'hourly',
        typical_range: {
            min: 50,
            median: 685,
            p95: 3299,
            max: 14500,
        },
        related_metrics: ['clv', 'basket_size', 'items_per_order'],
        common_filters: ['Order_Date >= DATEADD(month, -3, GETDATE())'],
        tags: ['sales', 'basket', 'kpi'],
        usage_frequency: 156,
        last_queried: '2025-09-29T09:45:00Z',
        embedding: {
            model: 'openai/text-embedding-3-small',
            dimension: 1536,
            vector: '[... 1536 dimensions ...]',
            generated_at: '2025-09-29T10:15:00Z',
            source:
                'metric_name + description + calculation_logic + common_business_questions',
        },
    },
    {
        metric_id: 'e8b4c6d1-9a7f-4e2c-b5d3-8f1a9c7e6b4d',
        type: 'business_metric',
        database_id: '46cb1ce1-848b-4561-bed7-1f35c1a81a5c',
        metric_name: {
            en: 'Active Loyalty Members',
            th: 'สมาชิกสะสมแต้มที่ใช้งานอยู่',
        },
        short_name: 'Active Members',
        description: {
            en: 'Count of customers who have made at least one purchase in the last 90 days and have non-zero point balance.',
            th: 'จำนวนลูกค้าที่มีการซื้อสินค้าอย่างน้อย 1 ครั้งใน 90 วันที่ผ่านมาและมีคะแนนคงเหลือมากกว่า 0',
        },
        business_domain: 'loyalty-program',
        calculation_logic:
            'COUNT DISTINCT customers with orders in last 90 days AND Point_Balance > 0',
        sql_expression:
            'SELECT COUNT(DISTINCT c.CustomerId) AS Active_Members FROM dbo.CRM_Customer c INNER JOIN dbo.CRM_Order o ON c.CustomerId = o.CustomerId WHERE o.Order_Date >= DATEADD(day, -90, GETDATE()) AND c.Point_Balance > 0',
        relevant_table_ids: [
            '02c6bbd5-0c74-4193-a9cb-a84e3ccd0429',
            'b1c181fd-3af6-4af9-9ce8-bb0fdd5ef884',
        ],
        relevant_column_ids: [
            'f3d3a3df-6c4a-4dba-b1b9-2d4cb1122334',
            'c2d62be6-6ef3-49a3-b5d4-0fa3b537ce96',
            'b8a47e73-145a-4b89-91cd-e743cde1a507',
        ],
        unit_of_measure: 'count',
        aggregation_type: 'COUNT_DISTINCT',
        grain: 'program',
        business_owner: 'loyalty-team',
        refresh_schedule: 'daily',
        typical_range: {
            min: 145000,
            median: 182000,
            p95: 198000,
            max: 210000,
        },
        related_metrics: ['churn_rate', 'enrollment_rate', 'point_redemption_rate'],
        common_filters: ["registration_date >= '2023-01-01'"],
        tags: ['loyalty', 'engagement', 'kpi'],
        usage_frequency: 89,
        last_queried: '2025-09-29T08:20:00Z',
        embedding: {
            model: 'openai/text-embedding-3-small',
            dimension: 1536,
            vector: '[... 1536 dimensions ...]',
            generated_at: '2025-09-29T10:15:00Z',
            source:
                'metric_name + description + calculation_logic + common_business_questions',
        },
    },
];
