<template>
  <section class="space-y-6">
    <header class="flex flex-col gap-2">
      <div class="flex items-center justify-between">
        <div>
          <h1 class="text-2xl font-semibold">Business Metrics</h1>
          <p class="text-sm text-muted-foreground">Define curated metrics with calculation logic, owners, and embedding coverage.</p>
        </div>
        <button class="rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground hover:opacity-90">
          New Metric
        </button>
      </div>
      <div class="flex flex-wrap gap-2 text-sm">
        <input class="w-full rounded-md border border-border bg-background px-3 py-2 md:w-72" placeholder="Search metrics" />
        <select class="rounded-md border border-border bg-background px-3 py-2">
          <option>Domain</option>
        </select>
        <select class="rounded-md border border-border bg-background px-3 py-2">
          <option>Refresh Status</option>
        </select>
      </div>
    </header>

    <div class="grid gap-4 lg:grid-cols-2">
      <Card v-for="metric in skeletonMetrics" :key="metric.id">
        <CardHeader>
          <div class="flex items-center justify-between">
            <CardTitle>{{ metric.name }}</CardTitle>
            <span class="rounded-full bg-muted px-2 py-0.5 text-xs text-muted-foreground">{{ metric.shortName }}</span>
          </div>
          <CardDescription>{{ metric.description }}</CardDescription>
        </CardHeader>
        <CardContent class="space-y-2 text-sm text-muted-foreground">
          <p><strong class="text-foreground">Owner:</strong> {{ metric.owner }}</p>
          <p><strong class="text-foreground">Refresh:</strong> {{ metric.refresh }}</p>
          <p><strong class="text-foreground">Usage:</strong> {{ metric.usage }}</p>
        </CardContent>
      </Card>
    </div>
  </section>
</template>

<script setup lang="ts">
import Card from '@/components/ui/Card.vue';
import CardHeader from '@/components/ui/CardHeader.vue';
import CardContent from '@/components/ui/CardContent.vue';
import CardTitle from '@/components/ui/CardTitle.vue';
import CardDescription from '@/components/ui/CardDescription.vue';

const skeletonMetrics = [
  {
    id: 'metric-1',
    name: 'Customer Lifetime Value',
    shortName: 'CLV',
    description: 'Total revenue generated by a customer across all orders since enrollment.',
    owner: 'crm-analytics',
    refresh: 'Daily',
    usage: '342 queries'
  },
  {
    id: 'metric-2',
    name: 'Average Order Value',
    shortName: 'AOV',
    description: 'Mean transaction value per order.',
    owner: 'sales-ops',
    refresh: 'Hourly',
    usage: '156 queries'
  }
];
</script>
